OMAP3: PM: CPUidle: include header for build breakage
Commit 78ed87d0a8b3b003e8b0e4c2736550bee0eb2859
(OMAP2+: PM: use off_mode_enabled as the global off mode flag)

introduced off_mode_enabled, however missed to include the required
header for the same. this causes breakage as follows:

 CC      arch/arm/mach-omap2/cpuidle34xx.o
 arch/arm/mach-omap2/cpuidle34xx.c: In function 'next_valid_state':
 arch/arm/mach-omap2/cpuidle34xx.c:160: error: 'off_mode_enabled'
 undeclared (first use in this function)

Change-Id: Id7361e6897b2dcd759c109edcf0f2890362fe590
Reported-by: Todd Poynor <toddpoynor@google.com>
Reported-by: Axel Haslam <axelhaslam@ti.com>
Signed-off-by: Nishanth Menon <nm@ti.com>