mmc: omap_hsmmc: fix build breakage
 commit 85255805d902a9f447ffd5d715deefb668152981
 Author: Dmitry Shmidt <dimitrysh@google.com>
 mmc: omap_hsmmc: Skip mmc suspend/resume ops for SDIO device

 breaks build with:
drivers/mmc/host/omap_hsmmc.c: In function 'omap_hsmmc_suspend':
drivers/mmc/host/omap_hsmmc.c:2364:42: error: dereferencing pointer to incomplete type
drivers/mmc/host/omap_hsmmc.c:2364:52: error: 'MMC_TYPE_SDIO' undeclared (first use in this function)
drivers/mmc/host/omap_hsmmc.c:2364:52: note: each undeclared identifier is reported only once for each function it appears in
drivers/mmc/host/omap_hsmmc.c: In function 'omap_hsmmc_resume':
drivers/mmc/host/omap_hsmmc.c:2426:42: error: dereferencing pointer to incomplete type
drivers/mmc/host/omap_hsmmc.c:2426:52: error: 'MMC_TYPE_SDIO' undeclared (first use in this function)

include card.h to prevent the breakage

Signed-off-by: Nishanth Menon <nm@ti.com>