OMAP: PM: NOOP: change prototype of omap_pm_get_dev_context_loss_count
with CONFIG_OMAP_PM_NOOP=y
build breaks with:
arch/arm/plat-omap/omap-pm-noop.c:313: error: conflicting types for 'omap_pm_get_dev_context_loss_count'
arch/arm/plat-omap/include/plat/omap-pm.h:361: note: previous declaration of 'omap_pm_get_dev_context_loss_count' was here

Reported-by: Vikram Pandita <vikram.pandita@ti.com>
Signed-off-by: Nishanth Menon <nm@ti.com>