OMAP2+: PMIC: fix build issues with pmic_update
Fixes two things:
a) ability to build with TPS disabled - fails with:
arch/arm/mach-omap2/pm.h fails at inline defn, "nt" instead of "int"
b) build warning:
arch/arm/mach-omap2/omap_pmic.c: In function 'omap_pmic_update':
arch/arm/mach-omap2/omap_pmic.c:84:4: warning: too many arguments for format
arch/arm/mach-omap2/omap_pmic.c:97:1: warning: control reaches end of non-void function

Reported-by: Colin Cross <ccross@google.com>
Acked-by: Colin Cross <ccross@google.com>
Signed-off-by: Nishanth Menon <nm@ti.com>